name = "file-upload-microservice"
main = "src/index.ts"
compatibility_date = "2024-12-13"

compatibility_flags = [ "nodejs_compat" ]

[vars]
CLOUDINARY_CLOUD_NAME = 
CLOUDINARY_API_KEY = 
CLOUDINARY_API_SECRET = 
JWT_SECRET = 
DATABASE_URL = 
WH_SECRET = 

[observability.logs]
enabled = true
